### ISSUE TITLE
[S] A&R Variance Report doesn't export notes in column

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/bcparks-ar-api#222]
### **How to Replicate**

Navigate to the A&R test environment and log in

Navigate to the Export Report page and navigate to the Variance tab

Generate a report and check the data in the report 

### **Expected Behavior:**

If there are notes available those notes should be listed in the Notes column

### **Notes**

The notes column is empty even when there are notes in Variance records.

**Comment by ashley-dhillon** [comment]
![Image](https://github.com/bcgov/bcparks-ar-api/assets/108755593/c3bc710a-696d-4b1e-adf2-90a673d1395d)

**Comment by manuji** [comment]
Tested on TEST: **Passed** ✅
* verified that this issue has been fixed. 
* Passing to PO review.

**Comment by JLWade** [comment]
working as expected in test - moving to done and can be pushed to prod

**Comment by kgorana** [comment]
**Linked to issues**
relates to
[x] ~https://github.com/bcgov/bcparks-ar-admin/issues/257#issue-1948528741~
