### ISSUE TITLE
[L] Connect Attendance & Revenue to Park Name Register

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-api#233]
Nightly cronjob should pull details from the data register, and store that in a separate table in order to determine if updates are required to the local DB, and to which park(s).  Coupling this with the index instructions below will ensure fast and efficient updates.

- Records for each subarea and activity will need to be updated.
```
{
 "pk": "0673::Backcountry Cabins",
 "sk": "201702",
 "activity": "Backcountry Cabins",
 "date": "201702",
 "isLegacy": true,
 "isLocked": true,
 "lastUpdated": "2023-04-04T21:32:34.317Z",
 "legacyData": {
  "legacy_backcountryCabinsNetRevenue": 0,
  "legacy_backcountryCabinsTotalAttendancePeople": 0
 },
 "orcs": "0116",
 "parkName": "Plumper Cove Marine Park",
 "subAreaId": "0673"
}
```

- Records for each park will need to be updated:
```
{
    "pk": "park::0363",
    "sk": "0189",
    "activities": {
        "wrapperName": "Set",
        "values": [
            "Backcountry Camping",
            "Day Use"
        ],
        "type": "String"
    },
    "bundle": "Sea-to-Sky",
    "managementArea": "Pemberton",
    "orcs": "0363",
    "parkName": "Joffre Lakes Park",
    "region": "South Coast",
    "roles": [
        "sysadmin",
        "0363:0189"
    ],
    "section": "Sea to Sky",
    "subAreaName": "Joffre Lakes"
}
```

- Config records also need updating:
```
{
 "pk": "config::0327",
 "sk": "Frontcountry Camping",
 "attendanceModifier": 3.2,
 "orcs": "0314",
 "parkName": "Porteau Cove Park",
 "subAreaId": "0327",
 "subAreaName": "Porteau Cove Walk-in"
}
```

Create an index against orcs/pk/sk in order to efficiently target the specific park name change.  Otherwise table scan will get very expensive/slow.  Index should target `pk: orcs`, no `sk` and atttribute `parkName` in the projection.  The NoSQL Workbench file should be created/updated accordingly to show the index.

**Acceptance Criteria:**
- park name data register is hooked up to A&R
- when park name changes in data register it is reflected in A&R within 24hrs (nightly cron job)

Notes:
- See issue/spike bcgov/parks-data-register#117 for reference.

**Comment by manuji** [comment]
@marklise , do you think running the cron job manually is possible? Please advise. Thanks!

**Comment by manuji** [comment]
Tested on TEST: Pending
* Verified that the name changes reflect on the Variance report and standard reports
* Verified that the name changes get reflected on the Enter Data pages and the dropdowns.
* Verified that the name changes get reflected on the Review Data page.

**Comment by JLWade** [comment]
Moving to blocked until data seeding with correct characters is complete and vanity urls are updated.

**Comment by JLWade** [comment]
moving to done
