### ISSUE TITLE
[S] Malformed date on small portion of A&R records - standard export report

### ISSUE THREAD

**Issue by kgorana** [bcgov/bcparks-ar-api#236]
## Description
In the standard exported record spreadsheet for A&R in prod, some records are showing up with malformed years & fiscal year columns (see attached).

This ticket is to determine and fix the root cause of these malformed records, and to restore the correct date values in affected records.
[malformed_date_records_A&R.xlsx](https://github.com/bcgov/bcparks-ar-api/files/13047940/malformed_date_records_A.R.xlsx)

## Acceptance Criteria
* Determine the root cause of this error, and fix if possible.
  * these records have data entered in the exported report, however in the UI in A&R admin they show as never updated. Use _Porpoise Bay Park - Porpoise Bay Dec 2022_ as an example 
  * If unable to determine reason for weird dates, let Jess know and just amend values to below
* Amend the affected data with the correct records (see below)
  * appears to only affect one bundle

## Notes
- **202** should be **2022**
- **203** should be **2023**
- **0202-203** should be **2022-2023**

**Comment by kgorana** [comment]
**Cameron Pettit** 
March 13, 2023 at 2:04 PM
_@Sally Haynes_ creating this bug to track this issue if you are interested in following along.

**Comment by cameronpettit** [comment]
Migration blurb for reference:


>This migration is to fix a handful of activity records that have incorrectly formated dates (and therefore sks). When trying to find an exhaustive list of these records, I did a database scan for all items where:

>  begins_with(pk: ':pk') AND begins_with(sk: 020)

>Obviously this is a very expensive query so I only scanned instances where ':pk'=0,1. I got a total of 31 results. Every single result has a 'lastUpdated' param of approximately the same time which indicates the malformed dates are a result of a bad migration and not something that is inherently wrong with the lambda that creates the activity records.

>It is difficult to tell exactly how the sk and date are mangled on these records. The dates all consist of 6 digits, where in other records, the first 4 digits are the year and the last two are the 2-digit month. I am going to assume that dates that begin with '0202' are for 2022 and dates that begin with '0203' are for 2023. This makes sense considering the last two digits of '0202' dates are 11 and 12, and the last two digits of '0203' dates is always 01, pertaining to the contiguous 3 month period between Nov 2022 and Jan 2023 before the 'lastUpdated' date of Feb 24 2023.

**Comment by cameronpettit** [comment]
Migration to be performed on prod environment only. No other environment has the same malformed record issue.

**Comment by cameronpettit** [comment]
Migration has been performed on prod.

**Comment by manuji** [comment]
Tested on PROD: **Passed**
* Verified that the newly exported report from PROD does not have malformed date values. 
* Passing this to PO review.

**Comment by JLWade** [comment]
woo! nice fix!
moving to done
