### ISSUE TITLE
A&R-> Exported report shows more than 2 decimal places on the Net Revenue column

### ISSUE THREAD

**Issue by kgorana** [bcgov/bcparks-ar-api#250]
## Description
**How to replicate:**
* Navigate to the A&R Admin on the Test environment
* Log in and navigate to the `Export Reports` page
* Generate a new report or download an already exported report
* Open the generated report and check all the `Net revenue` columns on the report

**Expected Behavior:**
* As it’s a currency value, I would assume the amount should be rounded up to 2 decimal places. @JLWade to confirm

**Issue:**
* All the `Net revenue` columns show more than 2 decimal places

  ![Image](https://github.com/bcgov/bcparks-ar-api/assets/145403218/e387d93e-177e-46e9-b3b0-d3558ab4b4e8)

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* verified that this issue has been fixed.

**Comment by JLWade** [comment]
only showing 2 decimals - moving to done
