### ISSUE TITLE
Park names of old records in exported reports still show outdated park names

### ISSUE THREAD

**Issue by manuji** [bcgov/bcparks-ar-api#288]
Scenario:

* navigate to the A&R on PROD: https://attendance-revenue.bcparks.ca/
* Navigate to the Export report page and export the general report and check the park names.

Issue:

* Some park names show both new and old park names for records in different years. 

Eg: Orcs -> 3883, check for the park name in the 2022 records and 2023 records.

**Comment by JLWade** [comment]
@manuji I think we can remove this one now right? the 3883 issue was due to a data issue not system.

**Comment by manuji** [comment]
Agreed, we can close this issue.
