### ISSUE TITLE
[M] Update 2 Garibaldi Sub-areas

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-api#311]
Update Garibaldi Park sub-areas as follows:
- Garibaldi Lake subarea changes to Rubble Creek
- Add backcountry cabins to Diamond Head

![Image](https://github.com/bcgov/bcparks-ar-api/assets/38668130/9b35e948-cb2e-481e-94d4-a1fee4b7a7af)

**Acceptance Criteria:**

Given that I am a A&R sys admin user (or a Garibaldi Park and Rubble Creek role),
When I search for Garibaldi Park in A&r to view or edit data,
then I can see the option of Rubble Creek sub-area (instead of Garibaldi Lake).

Given that I am an A&R sysadmin user (or a Garibaldi Park and Diamond Head role), 
When I try to enter data on Garibaldi Park, Diamond Head sub-area,
then I can see all activities available including backcountry cabins.

**Development Checklist:**

- [ ] ensure all records that used to belong to garibaldi park now have the rubble creek name (objects: park, subarea, activities, config, variances)
- [ ] persons with just the Rubble Creek role can only see rubble creek
- [ ] Diamond head has the backcountry cabins activity & config object

**Comment by cameronpettit** [comment]
Migration performed in PROD and DEV only, done in tandem with #313

**Comment by JLWade** [comment]
looks good in prod - moving to done
