### ISSUE TITLE
[S] Add two new parks to A&R

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-api#312]
Add two parks to A&R: Uncha Mountain Red Hills Park (9866) and Nenikekh/Nanika-Kidprice Park (0534).

![Image](https://github.com/bcgov/bcparks-ar-api/assets/38668130/8e416448-10f8-4e46-a855-a9a4fcf535d2)

**Acceptance Criteria:**

Given that I am a A&R sys admin user (or a Uncha Mountain Park sub-area role)
When I search for Uncha Mountain Red Hills Park in A&r to view or edit data,
then I can see the option of Red Hills Trail with Day Use activity.

Given that I am a A&R sys admin user (or Nenikekh/Nanika-Kidprice Park sub-area role)
When I search for Nenikekh/Nanika-Kidprice Park in A&r to view or edit data,
then I can see the option of Canoe Route with Backcountry Activity.

Given I have full permissions in redhat/keycloak
When I go to give a park operator or someone responsible for Uncha Mountain Red Hills Park it's sub-areas.
Then I can give them the correct permissions so they can enter data on the sub-areas they are responsible for.

Given I have full permissions in redhat/keycloak
When I go to give a park operator or someone responsible for Nenikekh/Nanika-Kidprice Park it's sub-areas.
Then I can give them the correct permissions so they can enter data on the sub-areas they are responsible for.

**Developer Checklist:**
Since we are using Data Register for park names the following steps need to be followed to add new parks to A&R
- [ ] Correct records are created in A&R with correct properties
- [ ] Ensure when records are created, there is an entry for that ORC # in the A&R local cache of names
- [ ] put N/A if there is no bundle

**Comment by cameronpettit** [comment]
@JLWade For  Nenikekh/Nanika-Kidprice Canoe Route Activity - Backcountry what? Camping or Cabins?

**Comment by JLWade** [comment]
camping - good catch

**Comment by cameronpettit** [comment]
Completed on Prod only.

**Comment by manuji** [comment]
Tested on PROD: **Passed**
* Verified tha the two parks are displayed on both Data regoster and A&R PROD environments. 
* Verified that the information are correct from DynamoDB.
* Verified that the items are available in keycloak and when users assigned with individual items, they have proper access on A&R. 
* Passing to PO review.

**Comment by JLWade** [comment]
added to prod - moving to done
