### ISSUE TITLE
[M] Update sub-area names under Cultus Lake Park

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-api#313]
Change the name of 2 sub-areas under Cultus Lake Park.

![Image](https://github.com/bcgov/bcparks-ar-api/assets/38668130/ceaa6ba6-4c84-4718-a4e7-f96b1bd4c6f3)

**Acceptance Criteria:**

Given I am a A&R sysadmin (or user with Cultus lake and subarea role),
when I enter or view data under Cultus Lake
then I see that there are two sub areas called Honeymoon Bay Group and Westside Group, instead of Cultus East Group and Cultus West Group as this aligns with website and reservation system.

**Dev Checklist:**

**Comment by cameronpettit** [comment]
Migration performed in PROD and DEV only, done in tandem with #311

**Comment by manuji** [comment]
Tested on PROD: **Passed**
* Verified that as an Admin as well as Facility specific role, I see the updated sub areas on the A&R PROD.
* Verified that exported report shows the updated sub area names.
* Verified that the data is correctly displayed from DynamoDB. 
* Passing to PO review.

**Comment by JLWade** [comment]
looks good in prod - moving to done
