### ISSUE TITLE
[S] Add backcountry camping activity to 2 sub-areas in Tweedsmuir Park

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-api#314]
Add backcountry camping activity to Alexander Mackenzie Trail and Rainbow Range Trailhead under Tweedsmuir Park. 

![Image](https://github.com/bcgov/bcparks-ar-api/assets/38668130/8087be09-e586-4b81-88c8-b7e1cf18c11d)

**Acceptance Criteria:**
Given I am an A&R sysadmin user (or have Tweedsmuir and correct sub-area role), 
When I enter or view data under Tweedsmuir Park, Alexander Mackenzie Trail 
Then I can add and/or view data under backcountry camping. 

Given I am an A&R sysadmin user (or have Tweedsmuir and correct sub-area role), 
When I enter or view data under Tweedsmuir Park, Rainbow Range Trailhead
Then I can add and/or view data under backcountry camping. 

**Dev Checklist:**

- [x] 1

**Comment by cameronpettit** [comment]
Completed in PROD only

**Comment by manuji** [comment]
Tested on PROD: **Passed**
* Verified that the Backcountry camping facility has been added to both 0455 and 0461 sub areas from A&R Admin portal and DynamoDB. 
* Passing to PO review.

**Comment by JLWade** [comment]
backcountry added to two subareas in prod - moving to done
