### ISSUE TITLE
[S] Add new sub-area to Roche Lake Park

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-api#316]
In A&R, add a new sub-area with Day Use activity under Roche Lake Park. 

![Image](https://github.com/bcgov/bcparks-ar-api/assets/38668130/0bd35ce8-fb11-464f-a676-12eacfd55176)

**Acceptance Criteria:**
Given I have a sysadmin role in A&R or the correct Roche Park and sub area permissions
When I go to Roche Lake Park in A&R
Then I can enter data under the ORV Trail sub-area under Day Use activity. 

Given I have full permissions in redhat/keycloak
When I go to give a park operator or someone responsible for Roche Lake a role for A&R
Then I can give them ROche Lake (6892) and ORV Trail permissions so they can enter data on that sub-area.

**Comment by cameronpettit** [comment]
Completed in Prod only.

**Comment by manuji** [comment]
Tested on PROD: **Passed**
* Verified that the new sub area and the facility has been added to the A&R using A&R Admin portal, DynamoDB.
* Verified that a user added only with permission to 6892:1022, has access and can add data from the A&R Admin portal. 
* Passing to PO review.

**Comment by JLWade** [comment]
looks good in prod - moving to done
