### ISSUE TITLE
Update sections on 2 parks: alexandra and Horne Lake

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-api#320]
Update the sections on the following two parks:

- Alexandra Bridge Park - change to: Thompson Cariboo (instead of South Coast)
- Horne Lake Caves Park - change to: North Coast

These two parks need updated sections in the database which populates in the exported reports. This change can be retroactive as well and applied to past data for these parks (may require a migration).

**Acceptance Criteria:**

Given that I am a A&R sys admin user (or a Alexandra Bridge Park or Horne Lake Caves Park role),
When I export a A&R general or variance report
then I can see the correct sections for each respective park in the csv download (Alexandra Bridge - Thompson Cariboo -- Horne Lake Caves Park - North Coast) and the correct sections are saved in the database (including past data).

**Comment by Christopher-walsh22** [comment]
I have run this migration in DEV and TEST environments. Following QA please let me know and I will run for PROD.

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* verified that the section has been updated on DynamoDB for all subarea items of the parks. 
* Unfortunately, the TEST do not have past data for the report to display. 
@Christopher-walsh22 , let's do the migration on PROD whenever you are ready.

**Comment by Christopher-walsh22** [comment]
@manuji I have run this migration against PROD environment now.

**Comment by manuji** [comment]
Tested on PROD: **Passed**
* Verified that the DynamoDb has been updated with the requested changes to the sub areas of two parks.
* Verified that the exported report shows the new Section names. 
* Passing to PO review.

**Comment by JLWade** [comment]
looks good to me - moving to done
