### ISSUE TITLE
[M] A&R: Update AWS SDK to V3

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-api#326]
#### Description:

Update AWS-SDK from V2 to V3. When using V2 it is fairly common to see warnings about outdated functionality along with a reminder V2 is nearing end of support. This task is go through the process of updating to V3, resolve all the warnings, and test the app to ensure any breaking changes caused from this update have been resolved.

[Amazons guide for Updating to V3](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating.html)

#### Acceptance Criteria:
A&R now uses AWS-SDK V3.

#### Development Checklist:

- [ ] all warnings about v2 to v3 have been resolved
- [x] Maintain functionality
- [x] API, Admin now using V3

#### Dependencies

- Blocked by #291 
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [x] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [x] UI meets accessibility requirements
  - [x] Unit tests are written
  - [x] Work is traceable in GitHub
  - [x] PR linked to ticket number
  - [x] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by cameronpettit** [comment]
A couple gotchas with this ticket for future conversions (https://github.com/bcgov/bcparks-ar-api/issues/326):

- Serverless uses SDK V2. Until we migrate to SAM, we will continue to get the 'Switch to v3' error message.
- `marshall` and `unmarshall` have changed, and seem to have difficulty with empty fields and nested objects. Be warned for future conversions. 

@manuji for testing this ticket, please do a full smoke test, in particular please try out the exporter functions for both activities and variances as they include the new V3 imports for AWS S3 and Lambda, which I am unable to test locally.

**Comment by manuji** [comment]
Tested on TEST: **Failed**
* Verified that the "Enter Data" page works fine and the variances are triggered accurately. 
* Verified that the "Review Data" page works fine. 

**Issues:**
* Error when trying to export the reports on "Export reports" page. When navigating to the page, two console errors are displayed and then it fails to export the standard report and variance report. 
* Also the page does not show previously exported reports: instead it says "No previous report found. Click generate report." even though there should be previously exported reports for both Standards and Variance. 

Note:
I also experienced an issue when trying to unlock a fiscal year right after locking one (recreated twice), but when I try to record the screen and recreate again, I could not. 

@cameronpettit FYI. Moving this ticket back to Todo.

**Comment by cameronpettit** [comment]
Gonna put a pin in this one until @Christopher-walsh22 and @davidclaveau have completed #291. At this time we would both be pushing to the same GH actions pipeline and this ticket will be easier to fix bugs on once they have their SAM stuff in. 

As per Manuji's earlier comment the export report functions are not working as AWS SDK V3's S3 functionality has changed since V2 and as we have no way of testing S3 stuff locally, I have to routinely push the code to DEV to troubleshoot. I will resume this once #291 is complete.
