### ISSUE TITLE
Convert Tests for Compatibility with SAM Build

### ISSUE THREAD

**Issue by davidclaveau** [bcgov/bcparks-ar-api#342]
#### Description:

One of the steps in converting the A&R app to use SAM is to convert the existing tests to work with the newly designated SAM directory within A&R. This will ensure our lambda functions and layers operate correctly and won't cause issues with CI/CD.

#### Acceptance Criteria:

- [ ] All tests run and pass
- [ ] READMEs are updated accordingly

#### Development Checklist:

- [ ] All tests are converted to work with the SAM changes, this mean path changes and conversion(s) for layers
- [ ] All tests run successfully and pass
- [ ] Update READMEs accordingly

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by manuji** [comment]
Tested on TEST: **Pending**
* Verified that the README file has been updated. 
* @Christopher-walsh22 & @davidclaveau , could you please guide me to find the unit tests mentioned in the Acceptance criteria?

**Comment by davidclaveau** [comment]
Hey @manuji!

These tests should be relatively the same as before the SAM update, and should all be located in several `__tests__` directories.

There are a few settings/setup/teardown files in the main `arSam` directory, and then the handlers and layers will have their own suite of tests in their respective `__tests__` directories, for example [Activity's tests will be found here](https://github.com/bcgov/bcparks-ar-api/blob/main/arSam/handlers/activity/__tests__/activity.test.js).

(And then the `package.json` file was tweaked slightly to accommodate these SAM-updated test suites when they're running during PR/Dev/Test/Prod deployment).

Let me know if that's all you needed, or if I can help with anything else!

**Comment by manuji** [comment]
Thank you @davidclaveau .

Tested and verified that the tests are included in the GitHub. 
Passing to PO review.
