### ISSUE TITLE
Change Null/Missing Export Columns for Easier Filtering

### ISSUE THREAD

**Issue by davidclaveau** [bcgov/bcparks-ar-api#374]
#### Description:

When I open up a recently downloaded Null/Missing export, I would like to see the Bundle, Park, Subarea, and Months in separate columns so it's easier to filter the data.

Right now, the Bundle, Park, Subarea and Months are in rows, but it would be easier to filter the data if these items were in columns instead.

#### Acceptance Criteria:

Given I am an A&R user
When I export the A&R Missing data
Then I get an excel spreadsheet where the Bundle, Park, Subarea, and Months are in separate columns

#### Development Checklist:

- [ ] Bundle, Park, Subarea, and Months are in separate columns
- [ ] The Activities and Years are in the same format

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by davidclaveau** [comment]
Hey @manuji this is ready to be moved to TEST now!

The Missing Export should now have `Bundle`, `Park`, `Subarea` and `Month` columns so it's easier for the user to filter the data in the spreadsheet.

This means the data is a little haphazard in how it's displayed, as items are still written by the old setup (by bundle, then park, then subarea, and then in a monthly order) - so it might look odd to see things printed out of order, but that's expected behaviour!

Let me know if you have any questions!

![Image](https://github.com/user-attachments/assets/8115adee-17a2-42ae-9708-a67b00abe5fb)

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this task has ben implemented and the exported report for missing/null values shows data in their respective columns with proper column headers. 
* Passing to PO review. 
![Image](https://github.com/user-attachments/assets/95990c7d-6dff-4f4b-948b-71828b45b3ef)

**Comment by davidclaveau** [comment]
I will aim to add a fix to this in [#377](https://github.com/bcgov/bcparks-ar-api/issues/377) when I apply an overall fix to the export!

**Comment by davidclaveau** [comment]
@manuji this fix will be in PR #383 

The issue arose when the exporter misinterpreted specialized names containing commas, like `ȽÁU,WELṈEW̱/John Dean Park`. The CSV file incorrectly split these names into separate cells, treating the comma as a delimiter. Names with commas should be properly "escaped" and displayed now that we know what to look for!

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* verified that the issue has been fixed and the report is looking good. 
* Passing to PO review.

**Comment by LindsayMacfarlane** [comment]
Took a quick look at the missing/null value exports. Can confirm the requested columns are displayed. Thank you @davidclaveau for your implementation of this request! And thank you @manuji for catching things in your thorough testing (you make it so easy for me :) )!
