### ISSUE TITLE
[M] A&R: Post-SAM Cleanup

### ISSUE THREAD

**Issue by davidclaveau** [bcgov/bcparks-ar-api#379]
#### Description:

Following the SAM frontend and backend updates, we should make sure that the old infrastructure is no longer available in all environments to prevent any old lambdas getting triggered, old data getting entered, etc.

#### Acceptance Criteria:

- [x] Old infrastructure is removed in AWS

#### Development Checklist:

- [x] Old API endpoints are no longer active

#### Blocked By:
- [x] Following the bug from #380, we should monitor logs to make sure no one else is hitting these endpoints in prod before fully cleaning up
  - [x] Make sure no one is hitting the old endpoints any longer (fix applied Oct. 18th)

**Wireframe(s):**

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [  Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
Sending for estimates.

**Comment by davidclaveau** [comment]
@LindsayMacfarlane this work has been completed!

I confirmed earlier today in A&R PROD that no one was hitting the old endpoints anymore, so we were in the clear to decommission the old resources. Here's an outline of what was removed:

- Remove old S3 buckets
- Remove old Cloudfront Distributions
- Remove old Dynamo DBs
  - First, snapshot the old (and the new... just in case) Dynamo DBs
    - config
    - nameCache
    - parksAr-xyg14p
- Remove old API Gateway
- Remove old Lambda Functions

A&R functionality remains the same and no issues with entering data, updating data, exporting reports, etc.

The same resources were removed from DEV and TEST, and those pesky old links have been removed from Confluence 😄 

Let me know if you have any questions or anything!

**Comment by LindsayMacfarlane** [comment]
Woohoo! This looks like a lot of work @davidclaveau and it is much appreciated. Especially grateful for the removal of the 'pesky' urls ;) 

Moving to done.
