### ISSUE TITLE
A&R: Consolidate Data Discrepancies between Old and New Databases

### ISSUE THREAD

**Issue by davidclaveau** [bcgov/bcparks-ar-api#380]
#### Description:

Following a bug where data is being entered into the old production database, we need to write a migration to find any missing or changed data from the old database (for all parks, subareas, variances, etc.) and consolidate it into the new production database so that it is up to date.

This should happen after #379 is completed.

#### Acceptance Criteria:

- [ ] New data from the old database is fully added to the new database
- [ ] Changed data from the old database is fully added to the new database

#### Blocked by

- #379

**Wireframe(s):**

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [  Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by davidclaveau** [comment]
@manuji this is ready for review!

For testing, I've exported files for the Standard, Variance, and Missing data from the _old_ database. Once this gets into TEST and I run the migration script I'll make sure to send you these files so you can compare to the exports/records for what exists after the migration.

It might not be the most fun way to test, but it should help show where some records were missing for an activity in August, September, etc. and how they are now present in the new exports after the migration.

Hope that makes sense! Let me know if you have any questions 😄

**Comment by manuji** [comment]
@davidclaveau , the TEST environment exports empty reports for the Standard report type.

**Comment by davidclaveau** [comment]
The issue with the empty report was due to a bug in [#254](https://github.com/bcgov/bcparks-ar-admin/issues/254).

**Comment by manuji** [comment]
QA note: Try to recreate the error with Missing report export feature with non sysadmin user.

**Comment by LindsayMacfarlane** [comment]
Will defer to @manuji 's amazing testing :) 

Thank you @davidclaveau for getting this done!

approved.
